<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-0OMSJ8N4" ignored="0" name="Listener Test case" tests="5" failures="1" timestamp="2020-05-03T12:30:51 IST" time="0.059" errors="0">
  <testcase name="test1" time="0.008" classname="com.testng.listener.sampleTestClass"/>
  <testcase name="test2" time="0.001" classname="com.testng.listener.sampleTestClass"/>
  <testcase name="test2" time="0.001" classname="com.testng.listener.sampleTestClass"/>
  <testcase name="test4" time="0.001" classname="com.testng.listener.sampleTestClass">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase name="three" time="0.003" classname="com.testng.listener.sampleTestClass">
    <failure type="java.lang.AssertionError" message="expected [7] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [7] but found [5]
at com.testng.listener.sampleTestClass.three(sampleTestClass.java:30)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- three -->
</testsuite> <!-- Listener Test case -->
